sudo: required

services:
  - docker

addons:
  hosts:
    - mesos-slave

language: java

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - ./gradlew dockerBuild

after_success:
  - ./gradlew integrationTest
  - ./gradlew jacocoTestReport coveralls