server:
  port: 9090

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

test-marathon-app:
  ribbon:
    ZonePattern: '.+\.(.+)'

logging:
  level:
    info.developerblog.spring.cloud.marathon: DEBUG