server:
  port: 9090

ribbon:
  ServerListRefreshInterval: 1000


test-marathon-app:
  ribbon:
    ZonePattern: '.+\.(.+)'

logging:
  level:
    info.developerblog.spring.cloud.marathon: DEBUG

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'