server:
  port: 8080

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    info.developerblog.spring.cloud.marathon: DEBUG